name: CI
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:8.9.1
        env:
          discovery.type: single-node
          xpack.security.enabled: 'false'
        ports: ['9200:9200']
        options: >-
          --health-cmd="curl -s http://localhost:9200/_cluster/health || true" --health-interval=10s --health-timeout=5s --health-retries=10

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        env:
          ELASTIC_HOST: localhost
          ELASTIC_PORT: 9200
        run: pytest -q


