version: '3.8'
services:
  traefik:
    image: traefik:v2.11
    command:
      - --providers.docker
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --api.insecure=true
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - web

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.9.1
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    volumes:
      - esdata_prod:/usr/share/elasticsearch/data
    networks:
      - backend

  kibana:
    image: docker.elastic.co/kibana/kibana:8.9.1
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    networks:
      - backend

  backend:
    build: ./backend
    env_file: .env
    labels:
      - "traefik.http.routers.backend.rule=Host(`logs.example.com`)"
      - "traefik.http.routers.backend.entrypoints=websecure"
    networks:
      - backend
      - web
    depends_on:
      - elasticsearch

  streamlit:
    build: ./streamlit_app
    env_file: .env
    labels:
      - "traefik.http.routers.streamlit.rule=Host(`dash.example.com`)"
      - "traefik.http.routers.streamlit.entrypoints=websecure"
    networks:
      - backend
      - web

volumes:
  esdata_prod:

networks:
  web:
    external: false
  backend:
    external: false


